const CATEGORY_HOLDER = {
	
	"Pasta" : 
	{
		"Sfoglia Lorda" : ["ricotta", "parmigiano",  "https://www.cibo360.it/cucina/mondo/spoja_lorda.htm"],
		"Tortelli Porri e Mortadella" : ["porri", "parmigiano", "mortadella", "prezzemolo", ""],
		"Cannelloni Ricotta e Spinaci" : ["ricotta", "spinaci", "parmigiano", ""],
		"Lasagna Zucca e Funghi" : ["zucca", "funghi", "burro", "vino bianco", "mozzarella", "parmigiano", "my-recipes/lasagna-zucca-funghi.html"],
		"Lasagna al Cavolo Rosso" : ["cavolo rosso", "mozzarella", "parmigiano", "my-recipes/lasagna-cavolo-rosso.html"],
		"Alla Norma" : ["pomodori", "melanzane", "parmigiano", ""],
		"Tonno Estiva" : ["tonno", "zucchine", "pomodorini", "prezzemolo", ""],
		"Pomodoro, Scamorza e Peperoncino" : ["pomodori", "scamorza", "peperoncino", ""],
		"Melanzane con Salsa di Pomodoro" : ["pomodori", "melanzane", "mozzarella", ""],
		"Crema di Zucca e Gorgonzola" : ["zucca", "gorgonzola", "cipolle", ""],
		"Gorgonzola e Radicchio" : ["gorgonzola", "radicchio", "noci", "https://www.lospicchiodaglio.it/ricetta/gnocchi-gorgonzola-noci-radicchio?refresh_ce"],
		"Pasta ripiena con tartufo": ["spinaci", "ricotta", "(olio di) tartufo", "https://www.fortunatiantonio.it/ravioli-al-tartufo-ricetta/"],
		"Gnocchi di Zucca ripieni di gorgonzola" : ["zucca", "gorgonzola", "patate", "salvia", "https://blog.giallozafferano.it/dolcesalatomiky/gnocchi-di-zucca-al-gorgonzola/"],
		"Aglione" : [""],
		"Aglio e olio" : [""],
		"Pesto Trapanese" : ["basilico", "pinoli", "pomodori", ""],
		"Pesto Genovese" : ["basilico", "pinoli", ""],
		"Pesto al Cavolo Rosso" : ["noci", "cavolo rosso", "peperoncino", ""],
		"Ravioli Ricotta e Spinaci" : ["ricotta", "spinaci", ""],
		"Pesto Pistacchi, Pomodorini, Porro" : ["pistacchi", "pomodorini", "porro", ""],
		"Pansoti con pesto alle noci" : ["erbette", "vino bianco", "ricotta", "noci", "pinoli", "rosmarino", ""],
		"Pere, Ricotta, Zafferano, Burro" : ["ricotta", "zafferano", "burro", ""],
		"Scarpinocc" : ["pane grattuggiato", "burro", ""],
		"Cappellacci alla Zucca" : ["zucca", "burro", "salvia", "https://www.lospicchiodaglio.it/ricetta/cappellacci-di-zucca"],
		"Tortellini" : ["carne macinata", "mortadella", "prosciutto crudo", ""],
		"Stracciatella" : ["brodo", "pane grattuggiato", ""],
		
	},

	"Panetteria" : 
	{
		"Pane Booty" : ["", "https://www.agrodolce.it/ricette/pane-per-tramezzini/"],
		"Condimenti per il pane" : ["zucchine", "funghi", "pomodori", "bavaria blu", "pesto di basilico", "pesto di menta", "maionese" , "olive nere", ""],
		"Calzone" : ["ricotta" , "mozzarella", "basilico", "prezzemolo", ""],
		"Crescia Estate" : ["strutto", "mortadella", "ricotta", "https://blog.giallozafferano.it/ricettevelociditania/piadina-sfogliata-marchigiana/"],
		"Crescia Mortadella, Maionese, Cipolle, Basilico" : ["basilico", "mortadella", ""],
		"Crescia Mortadella, Pinzimonio, Cipolle, Prezzemolo" : ["prezzemolo", "erba cipollina", "mortadella", "ricotta", ""],
		"Crescia Autunno" : ["spinaci", "funghi", "aceto balsamico", ""],
		"Crescia Provenzale" : ["tonno", "mozzarella", "pomodori", ""],
		"Crescia Scappatella" : ["funghi", "pomodori", "insalata", "maionese", ""],
		"Crescia Ortolana" : ["zucchine", "uova", "grana", "pomodori",  ""],
		"Crescia con Hummus" : ["lenticchie", "pomodori", ""],
		"French Toast" : ["pane", ""],
		"Strangolapreti" : ["salvia", "burro", "pane", "bietola", ""],
		"Canederli" : ["pane", "burro", "brodo", ""],
		"Polenta Funghi e Gorgonzola" : ["polenta", "gorgonzola", "funghi", "vino bianco", ""],
		"Pizzette di Sfoglia" : ["pomodori", "mozzarella", "burro", "my-recipes/sfoglia.html"],
		"Sfoglia Ricotta e Spinaci" : ["ricotta", "spinaci", "my-recipes/sfoglia.html"],
		"Pizza Margherita" : ["mozzarella", "pomodoro", ""],
		"Pizza Cipolla e Tonno" : ["cipolla rossa", "tonno", "mozzarella", ""],
		"Focaccia Cipolla e Gorgonzola" : ["cipolla", "gorgonzola", "https://www.tavolartegusto.it/ricetta/focaccia-morbida-ricetta-focaccia/"],
		"Focaccia Pomodori e Olive" : ["pomodori", "olive", "https://www.tavolartegusto.it/ricetta/focaccia-morbida-ricetta-focaccia/"],
	},

	"Frittura" : {
		"Gnocco" : [""],
		"Panzerotti Pomodoro e Mozzarella" : ["pomodori", "mozzarella", "cipolle", ""],
		"Panzerotti Salsiccia e Friarielli" : ["salsiccia", "friarielli", ""],
		"Panzerotti Nuvole" : ["ricotta", ""],
		"Kolokithokeftedes" : ["zucchine", "pomodorini", "feta", "cipollotto", "menta", "my-recipes/kolokithokeftedes.html"],
		"Tzatziki" : ["cetriolo", "yogurt greco", ""],
		"Reibekuchen" : ["patate", ""],
		"Olive Ascolane" : ["carne macinata", "olive grandi", "pane grattuggiato", ""],
		"Zucchine alla Romana" : ["zucchine", ""],
		"Mozzarella in Carrozza" : ["mozzarella", "pane", "pane grattuggiato", ""],
	},
		
	"Secondi" : {
		"Pinzimonio" : ["ricotta", "prezzemolo", ""],
		"Parmigiana" : ["zucchine", "mozzarella", "parmigiano", "my-recipes/parmigiana.html"],
		"Uova alla Diavola" : [""],
		"Insalata di Broccoli" : ["broccoli", "patate", "carote", ""],
		"Insalata affianco" : ["lattuga", "cetriolo", "pomodori", "pinoli", ""],
		"Sformato di Zucca e Carote" : ["zucca", "carote", "cipolle", ""],
		"Uova in Salsa di Pomodoro" : [""],
		
	},

	"Carne" : {
		"Käse-Lauchsuppe" : ["crème fraîche", "schmelzkäse", "porro", "carne macinata", ""],
		"Ragù" : ["carne macinata", "sedano", "cipolle", "carote", "passata", "vino rosso", ""],
		"Lasagna col Ragù" : ["ragù", ""],
		"Lasagna Bianca" : [""],
		"Bratwurst mit Sauerkraut" : ["Bratwurst", "Sauerkraut", ""],
		"Alla Filippo" : ["vino rosso", "panna", "cipolle", "salsiccia", ""],
		"Currywurst" :  ["Bratwurst", "pomodori", "brodo", "miele", "aceto di mele", "https://www.daringgourmet.com/best-german-curry-ketchup-for-currywurst/"],
	},

	"Dolci" : {
		"Waffles" : ["zucchero perlato", "burro", "lievito",  "my-recipes/waffles.html"],
		"Camille" : ["carote", "mandorle", "succo di arancia", ""],
		"Ottolenghi Cookies" : ["pere", "cioccolato bianco", "limone", "https://www.theguardian.com/food/2018/nov/24/pear-recipes-cheesecake-choc-chip-cookie-ginger-cake-yotam-ottolenghi"],
		"Pere e Vino" : ["pere", "vino rosso", "https://ricette.giallozafferano.it/pere-al-vino-rosso.html"],
		"Cicerchiata" : ["miele di acacia", "vino liquoroso", "https://blog.giallozafferano.it/quasimagia/cicerchiata-ricetta-di-carnevale-marche/"],
		"Panna Cotta" : ["panna", "agar agar", "frutti di bosco", ""],
		"Pancakes" : [""],
		"Milkshake" : ["fragole", "lamponi", "marmellata", "gelato fiordilatte", "my-recipes/milkshake.html"],
		"Cestini" : ["frutti di bosco", "https://www.misya.info/ricetta/cestini-di-frutta.htm"],
		"Bignè" : ["burro", "https://www.akkiapparicette.it/ricette/bigne-alla-crema-pasticcera-e-zabaione/"],
		"Profiteroles" : ["panna fresca", "cioccolato fondente", "cioccolato bianco", "https://ricette.giallozafferano.it/Profiteroles-al-cioccolato-bianco.html"],
		"Tiramisù" : ["mascarpone", "cacao amaro", "caffè", "savoiardi", ""],
		"Savoiardi" : ["https://www.tavolartegusto.it/ricetta/savoiardi/"],
		"Crepes, Kompott, Pinoli" : ["mele", "pinoli", ""],
	},
	
	"Fondamentali" : {
		"Farina" : ["farina", ""],
		"Uova" : ["uova", ""],
		"Aglio" : ["aglio", ""],
		"Cipolle" : ["cipolle", ""],
		"Passata di Pomodoro" : ["passata di pomodoro", ""],
		"Latte" : ["latte", ""],
		"Olio di Oliva" : ["olio di oliva", ""],
		"Olio di Girasole" : ["olio di girasole", ""],
		"Parmigiano" : ["parmigiano", ""],
		"Burro" : ["burro", ""],
		"Lievito di birra" : ["lievito di birra", ""],
		"Lievito per dolci" : ["lievito per dolci", ""],
		"Zucchero" : ["zucchero", ""],
		"Zucchero di canna" : ["zucchero di canna", ""],
		"Aceto Balsamico" : ["aceto balsamico", ""],
		"Zucchero" : ["zucchero", ""],
		"Sale" : ["sale", ""],
		"Pepe" : ["pepe", ""],
		"Rosmarino" : ["rosmarino", ""],
		"Timo" : ["timo", ""],
		"Noce Moscata" : ["noce moscata", ""],
		"Cannella " : ["cannella", ""],
		"Zafferano" : ["zafferano", ""],
		"Scottex" : ["scottex", ""],
		"Fazzoletti" : ["fazzoletti", ""],
		"Bagnoschiuma/Sapone" : ["bagnoschiuma/sapone", ""],
		"Dentifricio" : ["dentifricio", ""],
		"Detersivo" : ["detersivo", ""],
		"Spugne" : ["spugne", ""],
		"Guanti" : ["guanti", ""],
		"Carta Igienica" : ["carta igienica", ""],
		"Spray Pulizia" : ["spray pulizia", ""],
		"Spazzatura" : ["spazzatura", ""],
		"Lettiera" : ["lettiera", ""],
		"Cibo per Gattino" : ["cibo per gattino", ""],
		"Roba per Lavastoviglie" : ["roba per lavastoviglie", ""],
	}
}

