const CATEGORY_HOLDER = {
	
	"Pasta" : 
	{
		"Sfoglia Lorda" : ["ricotta", "parmigiano",  "https://www.cibo360.it/cucina/mondo/spoja_lorda.htm"],
		"Tortelli Porri e Mortadella" : ["porri", "parmigiano", "mortadella", "prezzemolo", ""],
		"Cannelloni Ricotta e Spinaci" : ["ricotta", "spinaci", "parmigiano", ""],
		"Lasagna Zucca e Funghi" : ["zucca", "funghi", "burro", "vino bianco", "mozzarella", "parmigiano", "my-recipes/lasagna-zucca-funghi.html"],
		"Lasagna al Cavolo Rosso" : ["cavolo rosso", "mozzarella", "parmigiano", "my-recipes/lasagna-cavolo-rosso.html"],
		"Alla Norma" : ["pomodori", "melanzane", "parmigiano", ""],
		"Tonno Estiva" : ["tonno", "zucchine", "pomodorini", "prezzemolo", ""],
		"Pasta fredda" : ["pomodori", "mozzarella", "basilico", ""],
		"Pomodoro, Scamorza e Peperoncino" : ["pomodori", "scamorza", "peperoncino", ""],
		"Melanzane con Salsa di Pomodoro" : ["pomodori", "melanzane", "mozzarella", ""],
		"Crema di Zucca e Gorgonzola" : ["zucca", "gorgonzola", "cipolle", ""],
		"Gorgonzola e Radicchio" : ["gorgonzola", "radicchio", "noci", "https://www.lospicchiodaglio.it/ricetta/gnocchi-gorgonzola-noci-radicchio?refresh_ce"],
		"Pasta ripiena con tartufo": ["spinaci", "ricotta", "(olio di) tartufo", "https://www.fortunatiantonio.it/ravioli-al-tartufo-ricetta/"],
		"Gnocchi di Zucca ripieni di gorgonzola" : ["zucca", "gorgonzola", "patate", "salvia", "https://blog.giallozafferano.it/dolcesalatomiky/gnocchi-di-zucca-al-gorgonzola/"],
		"Aglione" : [""],
		"Aglio e olio" : [""],
		"Pesto Trapanese" : ["basilico", "pinoli", "pomodori", ""],
		"Pesto Genovese" : ["basilico", "pinoli", ""],
		"Pesto al Cavolo Rosso" : ["noci", "cavolo rosso", "peperoncino", ""],
		"Ravioli Ricotta e Spinaci" : ["ricotta", "spinaci", ""],
		"Pesto Pistacchi, Pomodorini, Porro" : ["pistacchi", "pomodorini", "porro", ""],
		"Pansoti con pesto alle noci" : ["erbette", "vino bianco", "ricotta", "noci", "pinoli", "rosmarino", ""],
		"Pere, Ricotta, Zafferano, Burro" : ["ricotta", "zafferano", "burro", ""],
		"Scarpinocc" : ["pane grattuggiato", "burro", ""],
		"Cappellacci alla Zucca" : ["zucca", "burro", "salvia", "https://www.lospicchiodaglio.it/ricetta/cappellacci-di-zucca"],
		"Tortellini" : ["carne macinata", "mortadella", "prosciutto crudo", ""],
		"Stracciatella" : ["brodo", "pane grattuggiato", ""],
		"Ricette Marchigiane" : ["", "https://www.valcesano.com/ricette-marchigiane-tradizionali"],
		
	},

	"Panetteria" : 
	{
		"Pane Booty" : ["https://www.agrodolce.it/ricette/pane-per-tramezzini/"],
		"Panini morbidi" : ["https://www.misya.info/ricetta/panini-morbidoni.htm"],
		"Pettole" : ["", "https://blog.giallozafferano.it/fablesucre/pettole/"],
		"Crescia" : ["strutto", "https://blog.giallozafferano.it/ricettevelociditania/piadina-sfogliata-marchigiana/"],
		"Calzone" : ["ricotta" , "mozzarella", "basilico", "prezzemolo", ""],
		"French Toast" : [""],
		"Bruschetta alla Rita" : ["peperoni", "pomodori", "mozzarella", "zucchine", ""],
		"Piadina" : ["https://blog.giallozafferano.it/studentiaifornelli/piadina-senza-strutto/"],
		"Pasta Brisé" : [""],
		"Pita" : ["https://www.tavolartegusto.it/ricetta/pita-la-ricetta-originale-pita-greca/"],
		"Crespelle" : ["burro", ""],
		"Strangolapreti" : ["salvia", "burro", "pane", "bietola", ""],
		"Canederli" : ["pane", "burro", "brodo", ""],
		"Pizza" : ["mozzarella", "pomodori", "https://magazine.tognana.com/pizza-fatta-in-casa-con-il-fornetto-rotondo-sphera/"],
		"Focaccia" : [""],
		"Sfoglia" : ["ricotta", "spinaci", "my-recipes/sfoglia.html"],
		"Polenta" : ["polenta", ""],
		"Estate" : ["mortadella", "ricotta",],
		"Mortadella, Maionese, Cipolle, Basilico" : ["basilico", "mortadella", ""],
		"Autunno" : ["spinaci", "funghi", "aceto balsamico", ""],
		"Provenzale" : ["tonno", "mozzarella", "pomodori", ""],
		"Scappatella" : ["funghi", "pomodori", "insalata", "maionese", ""],
		"Ortolana" : ["zucchine", "uova", "grana", "pomodori",  ""],
	},

	"Frittura" : {
		"Gnocco" : ["my-recipes/gnocco.html"],
		"Panzerotti Pomodoro e Mozzarella" : ["pomodori", "mozzarella", "cipolle", ""],
		"Panzerotti Salsiccia e Friarielli" : ["salsiccia", "friarielli", ""],
		"Panzerotti Nuvole" : ["ricotta", ""],
		"Patate Fritte" : ["patate" ,"https://yt.artemislena.eu/watch?v=JiEQHFBxC2E"],
		"Kolokithokeftedes" : ["zucchine", "pomodorini", "feta", "cipollotto", "menta", "my-recipes/kolokithokeftedes.html"],
		"Reibekuchen" : ["patate", ""],
		"Olive Ascolane" : ["carne macinata", "olive", "pane grattuggiato", ""],
		"Zucchine alla Romana" : ["zucchine", ""],
		"Mozzarella in Carrozza" : ["mozzarella", "pane", "pane grattuggiato", ""],
	},
		
	"Secondi" : {
		"Parmigiana" : ["zucchine", "mozzarella", "parmigiano", "my-recipes/parmigiana.html"],
		"Uova alla Diavola" : [""],
		"Finocchi al Forno" : ["finocchi", "mozzarella", "https://www.cucchiaio.it/ricetta/finocchi-al-forno-con-mozzarella-e-uova/"],
		"Insalata di Broccoli" : ["broccoli", "patate", "carote", ""],
		"Sformato di Zucca e Carote" : ["zucca", "carote", "cipolle", ""],
		"Uova in Salsa di Pomodoro" : [""],
		"Torta di Frittata a Strati" : [""],
		"Patate Arrosto" : ["patate", "my-recipes/patate-arrosto.html"],
		"Feta al Forno" : ["feta", "pomodori", "cipolle rosse", "olive", "https://www.comeuno-chef.com/ricette/feta-al-forno"],
		
	},

	"Zuppe" : {
		"Zuppa di Noci" : ["noci", "panna", "https://www.cucchiaio.it/ricetta/ricetta-minestra-noci/"],
		"Zuppa d'Aglio" : ["https://www.buonissimo.it/lericette/3512_Zuppa_d_aglio"],
		"Zuppa di Castagne" : ["castagne", "porro", "https://www.lacucinaitaliana.it/ricetta/primi/zuppa-di-castagne/"],
		"Zuppa di Vino" : ["https://www.cucchiaio.it/ricetta/ricetta-zuppa-vino-valle-isarco/"],
		"Zuppa Imperiale" : ["https://ricette.giallozafferano.it/Zuppa-imperiale.html"],
	},

	"Dips" : {
		"Burro alle Erbe" : ["burro", "basilico", "prezzemolo", "https://www.ilclubdellericette.it/ricetta/burro-alle-erbe"],
		"Hummus di lenticchie" : ["lenticchie", "pomodori", ""],
		"Hummus di radicchio" : ["radicchio", "yogurt greco", ""],
		"Pinzimonio" : ["ricotta", "prezzemolo", ""],
		"Curry" : ["prezzemolo", "aglio", "zenzero", "curcuma", "chili" , "my-recipes/curry.html"],
		"Tzatziki" : ["cetriolo", "yogurt greco", ""],
		"Tirokafteri" : ["peperone", "feta", "yogurt greco", "https://erasmusu.com/it/blog-erasmus/ricette-erasmus/come-preparare-la-tradizionale-tirokafteri-salsa-greca-455871"],
	},

	"Carne" : {
		"Käse-Lauchsuppe" : ["crème fraîche", "schmelzkäse", "porro", "carne macinata", ""],
		"Ragù" : ["carne macinata", "sedano", "cipolle", "carote", "passata", "vino rosso", ""],
		"Lasagna col Ragù" : ["ragù", ""],
		"Lasagna Bianca" : [""],
		"Bratwurst mit Sauerkraut" : ["Bratwurst", "Sauerkraut", ""],
		"Alla Filippo" : ["vino rosso", "panna", "cipolle", "salsiccia", ""],
		"Currywurst" :  ["Bratwurst", "pomodori", "brodo", "miele", "aceto di mele", "https://www.daringgourmet.com/best-german-curry-ketchup-for-currywurst/"],
	},

	"Dolci" : {
		"Nutella" : ["zucchero di canna", "cioccolato", "nocciole" ,"my-recipes/nutella.html"],
		"Cioccolata Calda" : ["cioccolato", "nocciole", "panna", "https://www.davidezambelli.com/ricette/cioccolata-calda/"],
		"Ciambellone": ["https://blog.giallozafferano.it/rossellainpadella/ciambella-al-cioccolato-al-latte/"],
		"Waffles" : ["zucchero perlato", "burro", "lievito",  "my-recipes/waffles.html"],
		"Camille" : ["carote", "mandorle", "succo di arancia", ""],
		"Ottolenghi Cookies" : ["pere", "cioccolato bianco", "limone", "https://www.theguardian.com/food/2018/nov/24/pear-recipes-cheesecake-choc-chip-cookie-ginger-cake-yotam-ottolenghi"],
		"Pere e Vino" : ["pere", "vino rosso", "https://ricette.giallozafferano.it/pere-al-vino-rosso.html"],
		"Cicerchiata" : ["miele di acacia", "vino liquoroso", "https://blog.giallozafferano.it/quasimagia/cicerchiata-ricetta-di-carnevale-marche/"],
		"Panna Cotta" : ["panna", "agar agar", "frutti di bosco", ""],
		"Pancakes" : ["http://bressanini-lescienze.blogautore.espresso.repubblica.it/2015/07/06/le-ricette-scientifiche-i-pancake/"],
		"Torta Rovesciata all'Ananas" : ["ananas", "https://blog.giallozafferano.it/cuochinprogress/torta-rovesciata-allananas/"],
		"Milkshake" : ["fragole", "lamponi", "marmellata", "gelato fiordilatte", "my-recipes/milkshake.html"],
		"Cestini" : ["frutti di bosco", "https://www.misya.info/ricetta/cestini-di-frutta.htm"],
		"Bignè" : ["burro", "https://www.akkiapparicette.it/ricette/bigne-alla-crema-pasticcera-e-zabaione/"],
		"Profiteroles" : ["panna fresca", "cioccolato fondente", "cioccolato bianco", "https://ricette.giallozafferano.it/Profiteroles-al-cioccolato-bianco.html"],
		"Tiramisù" : ["mascarpone", "cacao amaro", "caffè", "savoiardi", ""],
		"Savoiardi" : ["https://www.tavolartegusto.it/ricetta/savoiardi/"],
		"Crepes, Kompott, Pinoli" : ["mele", "pinoli", ""],
	},
	
	"Fondamentali" : {
		"Farina" : ["farina", ""],
		"Uova" : ["uova", ""],
		"Aglio" : ["aglio", ""],
		"Cipolle" : ["cipolle", ""],
		"Patate" : ["patate", ""],
		"Sedano" : ["sedano", ""],
		"Carote" : ["carote", ""],
		"Passata di Pomodoro" : ["passata di pomodoro", ""],
		"Latte" : ["latte", ""],
		"Olio di Oliva" : ["olio di oliva", ""],
		"Olio di Girasole" : ["olio di girasole", ""],
		"Parmigiano" : ["parmigiano", ""],
		"Burro" : ["burro", ""],
		"Lievito di birra" : ["lievito di birra", ""],
		"Lievito per dolci" : ["lievito per dolci", ""],
		"Zucchero" : ["zucchero", ""],
		"Zucchero di canna" : ["zucchero di canna", ""],
		"Aceto Balsamico" : ["aceto balsamico", ""],
		"Zucchero" : ["zucchero", ""],
		"Sale" : ["sale", ""],
		"Pepe" : ["pepe", ""],
		"Rosmarino" : ["rosmarino", ""],
		"Timo" : ["timo", ""],
		"Noce Moscata" : ["noce moscata", ""],
		"Cannella " : ["cannella", ""],
		"Zafferano" : ["zafferano", ""],
		"Scottex" : ["scottex", ""],
		"Fazzoletti" : ["fazzoletti", ""],
		"Bagnoschiuma/Sapone" : ["bagnoschiuma/sapone", ""],
		"Dentifricio" : ["dentifricio", ""],
		"Detersivo" : ["detersivo", ""],
		"Spugne" : ["spugne", ""],
		"Guanti" : ["guanti", ""],
		"Carta Igienica" : ["carta igienica", ""],
		"Spray Pulizia" : ["spray pulizia", ""],
		"Spazzatura" : ["spazzatura", ""],
		"Lettiera" : ["lettiera", ""],
		"Cibo per Gattino" : ["cibo per gattino", ""],
		"Roba per Lavastoviglie" : ["roba per lavastoviglie", ""],
	},

	"Siti di Riferimento" : {
		"Gamoto.net, sito del dizionario di Latino" : ["https://www.gamoto.net/ricette-cucina/"]
	}
}

